version: '3.4'

services:
  neo4j:
    container_name: neo4j
    image: neo4j:3.4.5
    restart: on-failure
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/import:/import
      - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_security_procedures_unrestricted=algo.*,apoc.*
    ports:
      - 7687:7687
      - 7474:7474
